#!/usr/env bash

# Required settings
export GITZEN_DJANGO_SECRET_KEY="SOMETHINGSECRET!"
export GITZEN_GITHUB_CLIENT_ID="YOUR_OAUTH2_ID"
export GITZEN_GITHUB_CLIENT_SECRET="YOUR_OAUTH2_SECRET"
export GITZEN_ABSOLUTE_SITE_URL="http://example.herokuapp.com"
export GITZEN_DEFAULT_FROM_EMAIL="notifications@example.com"
export GITZEN_EMAIL_HOST="smtp.example.com"
export GITZEN_SMTP_USER="exampleUser"
export GITZEN_SMTP_PASSWORD="SOMETHINGSECRET"

# Optional settings
#export GITZEN_DEBUG="False"
#export GITZEN_EMAIL_PORT="25"
#export GITZEN_MEDIA_ROOT="/opt/gitzen/upload"
#export GITZEN_MEDIA_URL="http://example.herokuapp.com/upload/"
#export GITZEN_STATIC_ROOT="/opt/gitzen/static"
#export GITZEN_STATIC_URL="http://example.herokuapp.com/static/"

# Local development settings
export DATABASE_URL="postgres://dbuser:dbpw@localhost/dbname"
